services:
  ddns-client:
    container_name: ddns-client
    restart: always
    build: .
    env_file:
      - .env
    volumes:
      - ./logs:/usr/src/app/logs
    networks:
      - ddns-client

networks:
  ddns-client:
    name: ddns-client